added name and id to makefile

diff --git a/proj0/Makefile~ b/proj0/Makefile~
--- a/proj0/Makefile~
+++ b/proj0/Makefile~
@@ -9,7 +9,7 @@ clean:
 dist: default
 	tar -czf lab0-304735411.tar.gz $(tarred_files)
 
-check: default testInvalidArg segFaultTest inputErrorTest
+check: default testInvalidArg segFaultTest inputErrorTest outputErrorTest successfulCopyTest
 
 testInvalidArg:
 	echo | ./lab0 --invalidarg &> /dev/null; \
@@ -45,3 +45,21 @@ outputErrorTest:
 	else \
 	echo "test passed for unable to open/write to output file"; \
 	fi
+	chmod u+w output.txt
+	rm input.txt output.txt
+
+successfulCopyTest:
+	echo "input file" > input.txt; \
+	./lab0 --input input.txt --output output.txt &> /dev/null; \
+	if [[ $$? -ne 0 ]]; then \
+	echo "test failed for proper exit code when copied"; \
+	else \
+	echo "test passed for proper exit code when copied"; \
+	fi; \
+	cmp input.txt output.txt; \
+        if [[ $$? -ne 0 ]]; then \
+        echo "test failed for input file matches output file"; \
+        else \
+        echo "test passed for input matches output"; \
+        fi
+	rm input.txt output.txt
